from social.exceptions import AuthAlreadyAssociated
from social.pipeline.social_auth import social_user as _social_user


def social_user(backend, uid, user=None, *args, **kwargs):
    try:
        pass
    except Exception, e:
        raise e
